/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type TicketService = "AC Repair" | "Appliance Repair" | "Carpenter" | "Cleaning" | "Electrician" | "Plumbing";

export type TicketStatus = "Accepted" | "Arrived" | "Assigned" | "Completed" | "InProgress";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface OtpCodes {
  code: string;
  consumedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  phone: string;
}

export interface ServiceAreas {
  areaCode: string;
  createdAt: Generated<Timestamp>;
  locality: string;
  localityName: string;
  subLocality: string;
  subLocalityName: string;
}

export interface Shops {
  areaCode: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  latitude: number | null;
  locality: string;
  localityName: string;
  longitude: number | null;
  ownerContact: string;
  photoUrl: string;
  shopName: string;
  subLocality: string;
  subLocalityName: string;
}

export interface Technicians {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  leadsRemaining: Generated<number>;
  name: Generated<string>;
  online: Generated<boolean>;
  phone: string;
  updatedAt: Generated<Timestamp>;
  walletPaise: Generated<number>;
}

export interface TechnicianSessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  technicianId: string;
  token: string;
}

export interface Tickets {
  acceptedAt: Timestamp | null;
  address: string;
  arrivedAt: Timestamp | null;
  bookingFee: Generated<number>;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  createdByShop: string | null;
  customerContact: string;
  customerName: string;
  id: Generated<string>;
  preferredTime: string;
  service: TicketService;
  serviceDescription: Generated<string>;
  startedAt: Timestamp | null;
  status: Generated<TicketStatus>;
  technicianId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  otpCodes: OtpCodes;
  serviceAreas: ServiceAreas;
  shops: Shops;
  technicians: Technicians;
  technicianSessions: TechnicianSessions;
  tickets: Tickets;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const TicketStatusArrayValues: [TicketStatus, ...TicketStatus[]] = ["Accepted","Arrived","Assigned","Completed","InProgress"];
export const TicketServiceArrayValues: [TicketService, ...TicketService[]] = ["AC Repair","Appliance Repair","Carpenter","Cleaning","Electrician","Plumbing"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.